analyzers:
  nemesis:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Monsterborg
    find_and_remove_prefix: 'nemesis_base: '
    expected: ['nemesis_base: battery_status','nemesis_base: software_status']
    timeout: 5.0
