/* Generated by Cython 0.23.4 */

#include <Python.h>

#ifndef __PYX_HAVE__ThunderBorgCythonMock
#define __PYX_HAVE__ThunderBorgCythonMock

struct c_ThunderBorg;

/* "ThunderBorgCythonMock.pyx":2
 *
 * cdef public class ThunderBorg [object c_ThunderBorg, type c_Thunderborg_t]:
 * # <<<<<<<<<<<<<<
 *
 *
 */
struct c_ThunderBorg {
  PyObject_HEAD struct __pyx_vtabstruct_21ThunderBorgCythonMock_ThunderBorg
      *__pyx_vtab;
};

#ifndef __PYX_HAVE_API__ThunderBorgCythonMock

#ifndef __PYX_EXTERN_C
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#endif

#ifndef DL_IMPORT
#define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) c_Thunderborg_t;

__PYX_EXTERN_C DL_IMPORT(struct c_ThunderBorg) * buildThunderBorg(void);
__PYX_EXTERN_C DL_IMPORT(PyObject) *
    SetMotor1Wrapper(struct c_ThunderBorg *, double);

#endif /* !__PYX_HAVE_API__ThunderBorgCythonMock */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initThunderBorgCythonMock(void);
#else
PyMODINIT_FUNC PyInit_ThunderBorgCythonMock(void);
#endif

#endif /* !__PYX_HAVE__ThunderBorgCythonMock */
